server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_DB
    username: postgres
    password: admin1302
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic:
    notifications-validated: notifications.validated